=== amillet2001/WMA4B-MT-LAB-EX/argueza_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="portfolio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="home" type="homeType"/>
        <xs:element name="about" type="aboutType"/>
        <xs:element name="resume" type="resumeType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="homeType">
    <xs:sequence>
      <xs:element name="hero">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="image">
              <xs:complexType>
                <xs:attribute name="src" type="xs:string" use="required"/>
                <xs:attribute name="alt" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="aboutType">
    <xs:sequence>
      <xs:element name="content" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="resumeType">
    <xs:sequence>
      <xs:element name="educBackground">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ul">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="li" type="xs:string" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="hobbies">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="ul">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="li" type="xs:string" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/argueza_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="argueza_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="argueza_schema.xsd">

  <home>
    <hero>
      <image src="../../../img/argueza.png" alt="Profile Picture"/>
      <name>Ervine Kirby V. Argueza</name>
      <description>Software Developer</description>
    </hero>
  </home>
  <about>
    <content> Hi! My name is Ervine Argueza, and I enjoy playing video games, editing, and coding simple projects.</content>
  </about>
  <resume>
    <educBackground>
      <ul>
        <li>Ecumenical Christian College (2010-2016)</li>
        <li>Ecumenical Christian College (2016–2020)</li>
        <li>Golden Olympus Colleges (2020–2022)</li>
      </ul>
    </educBackground>
    <hobbies>
      <title>Hobbies</title>
      <ul>
        <li>Gaming</li>
        <li>Editing</li>
        <li>Coding</li>
        
      </ul>
    </hobbies>
  </resume>
</portfolio>
