=== amillet2001/WMA4B-MT-LAB-EX/Bilaya_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="portfolio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" type="studentType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="studentType">
    <xs:sequence>
      <xs:element name="firstName" type="xs:string"/>
      <xs:element name="middleName" type="xs:string"/>
      <xs:element name="lastName" type="xs:string"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element name="phone" type="xs:string"/>
      <xs:element name="aboutMe" type="xs:string"/>
      <xs:element name="skills">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="skill" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="education">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="degree" type="degreeType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="hobbies">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="hobby" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="degreeType">
    <xs:sequence>
      <xs:element name="degreeType" type="xs:string"/>
      <xs:element name="field" type="xs:string"/>
      <xs:element name="institution" type="xs:string"/>
      <xs:element name="year" type="xs:gYear"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="projectType">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="technologies" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/bilaya_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bilaya_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bilaya_schema.xsd">
  <student>
    <firstName>Antonio Miguel</firstName>
    <middleName>Acosta</middleName>
    <lastName>Bilaya</lastName>
    <section> WMA 4B </section>
    <email>bilayaantoniomiguel@gmail.com</email>
    <phone>09635159774</phone>
    <aboutMe>Passionate software engineering student with expertise in web technologies and data structuring. Experienced in XML-based solutions for portfolio management and document transformation.</aboutMe>
    <skills>
      <skill>HTML</skill>
      <skill>CSS</skill>
      <skill>JavaScript</skill>
    </skills>
    <education>
      <degree>
        <degreeType>Bachelor</degreeType>
        <field>Information Technology</field>
        <institution>University of Tarlac</institution>
        <year>2025</year>
      </degree>
    </education>
    <hobbies>
      <hobby>Cooking</hobby>
      <hobby>Gaming</hobby>
      <hobby>Basketball</hobby>
    </hobbies>
  </student>
</portfolio>
