=== amillet2001/WMA4B-MT-LAB-EX/delacruz-c_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="myPortfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personalInfo" type="personalInfoType"/>
                <xs:element name="hobbies" type="hobbiesType"/>
                <xs:element name="mySkills" type="skillsType"/>
                <xs:element name="educationalBackground" type="educationBackgroundType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="personalInfoType">
        <xs:sequence>
            <xs:element name="fullName" type="xs:string"/>
            <xs:element name="phoneNum" type="xs:string"/>
            <xs:element name="birthDate" type="xs:string"/>
            <xs:element name="place" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="course" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hobbiesType">
        <xs:sequence>
            <xs:element name="hobby" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="skillsType">
        <xs:sequence>
            <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="educationBackgroundType">
        <xs:sequence>
            <xs:element name="education" type="educationType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="educationType">
        <xs:sequence>
            <xs:element name="level" type="xs:string"/>
            <xs:element name="schoolName" type="xs:string"/>
            <xs:element name="yearGraduated" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/delacruz-c_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="delacruz-c_transform.xsl" type="text/xsl"?>

<myPortfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="delacruz-c_schema.xsd">

    <personalInfo>
      <fullName>Christian Dela Cruz</fullName>
      <phoneNum>09763094881</phoneNum>
      <birthDate>May 18 2002</birthDate>
      <place>Tarlac City, Tarlac</place>
      <email>delacruz131@gmail.com</email>
      <course>BSIT Specialized in Network Administration</course>
    </personalInfo>

    <hobbies>
      <hobby>Playing Video Games</hobby>
      <hobby>Watching Movies/Series</hobby>
      <hobby>Editing Videos/Photos</hobby>
      <hobby>Playing Guitar</hobby>
    </hobbies>

    <mySkills>
      <skill>HTML</skill>
      <skill>CSS</skill>
      <skill>Video Editing</skill>
      <skill>Photo Editing</skill>
      <skill>Web Design</skill>
      <skill>Networking</skill>
    </mySkills>

    <educationalBackground>
      <education>
        <level>Senior High School</level>
        <schoolName>Tarlac State University - Senior High School</schoolName>
        <yearGraduated>2020</yearGraduated>
      </education>
      <education>
        <level>College</level>
        <schoolName>Tarlac State University - College of Computer Studies</schoolName>
        <yearGraduated>Present</yearGraduated>
      </education>
    </educationalBackground>


</myPortfolio>
