=== amillet2001/WMA4B-MT-LAB-EX/delacruz_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="portfolio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="home" type="homeType"/>
        <xs:element name="about" type="aboutType"/>
        <xs:element name="resume" type="resumeType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="homeType">
    <xs:sequence>
      <xs:element name="hero">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="image">
              <xs:complexType>
              </xs:complexType>
            </xs:element>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="detail" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="aboutType">
    <xs:sequence>
      <xs:element name="content" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="resumeType">
    <xs:sequence>
      <xs:element name="educationalBackground">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ul">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="li" type="xs:string" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Hobbies">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="ul">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="li" type="xs:string" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/delacruz_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="delacruz_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="delacruz_schema.xsd">
    
  <home>
    <hero>
      <name> John Carlo H. Dela Cruz </name>
      <detail> Student </detail>
    </hero>
  </home>
  <about>
    <content>Hello, I am John Carlo H. Dela Cruz, a 22-year-old boy who is exploring himself. I am on a journey to understand who I truly am—what I love, what I want, and what makes me unique.</content>
  </about>
  <resume>
    <educationalBackground>
      <ul>
        <li>San Jose Elementary School (2010 – 2016)</li>
        <li>San Manuel High School (2016 – 2020)</li>
        <li>San Manuel High School (2020 – 2022)</li>
      </ul>
    </educationalBackground>
    <hobbies>
      <title>Hobbies</title>
      <ul>
        <li>Gaming</li>
        <li>Reading Manhwa</li>
        <li>Watching Movies and Anime </li>
      </ul>
    </hobbies>
  </resume>
</portfolio>
