=== amillet2001/WMA4B-MT-LAB-EX/pabustan_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="studentType">
        <xs:sequence>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="course" type="xs:string"/>
            <xs:element name="yearlevel">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="activityType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="grade">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="skillType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="details" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="portfolio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="studentType"/>
                <xs:element name="activity" type="activityType" maxOccurs="unbounded"/>
                <xs:element name="skill" type="skillType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/pabustan_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="pabustan_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="pabustan_schema.xsd">
    <student>
        <id>2022123456789</id>
        <lastname>Pabustan</lastname>
        <firstname>Mary Anne</firstname>
        <course>BS Information Technology</course>
        <yearlevel>4th yr</yearlevel>
        <email>ahn.mweewi@gmail.com</email>
    </student>
    
    <activity type="Laboratory">
        <name>Laboratory Activity 2: XML Series</name>
        <date>2025-11-18</date>
        <description>Completed initial file creation and linking.</description>
    </activity>
    
    <activity type="Capstone">
        <name>Reflectify</name>
        <date>2025-11-18</date>
        <description>A Gamified LMS with Spaced Repetition Algorithm and Flashcard Automation using GPT-4o mini .</description>
    </activity>
    
    <skill>
        <name>Programming</name>
        <details>Java, Python, JavaScript</details>
    </skill>
    
    <skill>
        <name>Web Technologies</name>
        <details>HTML, CSS, XML, XSLT</details>
    </skill>
</portfolio>
