=== amillet2001/WMA4B-MT-LAB-EX/rufino_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="portfolio">
        <xs:complexType>
            <xs:sequence>
            
                <xs:element name="student">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="course" type="xs:string"/>
                            <xs:element name="year" type="xs:string"/>

                            <xs:element name="skills">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
 
                <xs:element name="projects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="project" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== amillet2001/WMA4B-MT-LAB-EX/rufino_portfolio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="rufino_transform.xsl"?>
<portfolio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="rufino_schema.xsd">

    <student>
        <name>Lorelyn Marie S. Rufino</name>
        <course>BSIT-WMA</course>
        <year>4th year</year>
        <skills>
            <skill>HTML</skill>
            <skill>CSS</skill>
            <skill>Web designer</skill>
        </skills>
    </student>

    <projects>
        <project>
            <title>My portfolio</title>
            <description>Created a simple portfolio.</description>
        </project>
        <project>
            <title>Portfolio Website</title>
            <description>Designed a personal website using HTML and CSS.</description>
        </project>
    </projects>

</portfolio>
